name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
    steps:
    - name: Check out repo
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade -r requirements-dev.txt
    - name: Build package
      run: |
        python pre_setup.py
        python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1.12
  send-pull-request:
    uses: openkim/developer-platform/.github/workflows/upversion-pypi-package-and-send-pr.yml@main
    secrets: inherit
